---
- name: Create clawdbot system user
  ansible.builtin.user:
    name: clawdbot
    comment: "Clawdbot Service User"
    system: true
    shell: /bin/bash
    create_home: true
    home: /home/clawdbot
    state: present

- name: Set clawdbot user as primary user for installation
  ansible.builtin.set_fact:
    clawdbot_user: clawdbot
    clawdbot_home: /home/clawdbot
